package com.managesc.app.github

import com.managesc.app.data.Prefs
import com.managesc.app.data.Vps
import com.managesc.app.data.VpsDbHelper
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import retrofit2.http.*
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

data class GhContentRequest(
    val message: String,
    val content: String,        // base64
    val sha: String? = null      // required when updating existing file
)

data class GhContentResponse(
    val sha: String?,
    val content: Map<String, Any>?
)

interface GitHubApi {
    @Headers("Accept: application/vnd.github+json")
    @retrofit2.http.GET("repos/{user}/{repo}/contents/{path}")
    suspend fun getFile(
        @retrofit2.http.Path("user") user: String,
        @retrofit2.http.Path("repo") repo: String,
        @retrofit2.http.Path("path") path: String
    ): retrofit2.Response<GhContentResponse>

    @Headers("Accept: application/vnd.github+json")
    @retrofit2.http.PUT("repos/{user}/{repo}/contents/{path}")
    suspend fun putFile(
        @retrofit2.http.Path("user") user: String,
        @retrofit2.http.Path("repo") repo: String,
        @retrofit2.http.Path("path") path: String,
        @Body body: GhContentRequest
    ): retrofit2.Response<GhContentResponse>
}

object GitHubSync {
    private fun api(token: String): GitHubApi {
        val client = OkHttpClient.Builder()
            .addInterceptor { chain ->
                val req = chain.request().newBuilder()
                    .addHeader("Authorization", "Bearer $token")
                    .build()
                chain.proceed(req)
            }
            .addInterceptor(HttpLoggingInterceptor().apply {
                level = HttpLoggingInterceptor.Level.BASIC
            })
            .build()
        return Retrofit.Builder()
            .baseUrl("https://api.github.com/")
            .client(client)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(GitHubApi::class.java)
    }

    /**
     * Format file sesuai Code.gs: "### username expiry_date ip_address"
     */
    private fun buildFileContent(list: List<Vps>): String {
        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        val today = sdf.format(Date())
        val sb = StringBuilder()
        sb.append("# VPS List — generated by ManageSC-Android\n")
        sb.append("# format: ### username expiry ip\n")
        sb.append("# updated: $today\n\n")
        for (v in list) {
            sb.append("### ${v.username} ${v.masaAktif} ${v.ipVps}\n")
        }
        return sb.toString()
    }

    /**
     * Push daftar VPS ke GitHub. Mengembalikan true jika sukses.
     * Catatan: implementasi ini meng-UPLOAD konten baru; untuk update file yang sudah ada
     * diperlukan SHA dari GET terlebih dahulu. Untuk simplifikasi, kita GET dulu lalu PUT.
     */
    suspend fun sync(context: android.content.Context): String {
        val token = Prefs.getGhToken(context)
        if (token.isBlank()) return "Token GitHub kosong"
        val user = Prefs.getGhUser(context)
        val repo = Prefs.getGhRepo(context)
        val path = Prefs.getGhPath(context)
        if (user.isBlank() || repo.isBlank() || path.isBlank())
            return "Konfigurasi GitHub belum lengkap"

        val list = VpsDbHelper(context).getAll()
        val content = buildFileContent(list)
        val b64 = android.util.Base64.encodeToString(
            content.toByteArray(Charsets.UTF_8), android.util.Base64.NO_WRAP
        )
        return try {
            val api = api(token)
            // Coba GET sha dulu (jika file ada)
            var sha: String? = null
            try {
                val getResp = api.getFile(user, repo, path)
                if (getResp.isSuccessful) sha = getResp.body()?.sha
            } catch (_: Exception) { /* file mungkin belum ada */ }

            val resp = api.putFile(
                user, repo, path,
                GhContentRequest("Update VPS list from ManageSC-Android", b64, sha)
            )
            if (resp.isSuccessful) "Berhasil sync ${list.size} data ke GitHub"
            else "Gagal: ${resp.code()} ${resp.errorBody()?.string()?.take(200)}"
        } catch (e: Exception) {
            "Error: ${e.message}"
        }
    }
}
