package com.managesc.app.github

import com.managesc.app.data.Prefs
import com.managesc.app.data.Vps
import com.managesc.app.data.VpsDbHelper
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import retrofit2.http.*
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

data class GhContentRequest(
    val message: String,
    val content: String,        // base64
    val sha: String? = null      // required when updating existing file
)

data class GhContentResponse(
    val sha: String? = null,
    val content: String? = null
)

interface GitHubApi {
    @Headers("Accept: application/vnd.github+json")
    @retrofit2.http.GET("repos/{user}/{repo}/contents/{path}")
    suspend fun getFile(
        @retrofit2.http.Path("user") user: String,
        @retrofit2.http.Path("repo") repo: String,
        @retrofit2.http.Path("path") path: String
    ): retrofit2.Response<GhContentResponse>

    @Headers("Accept: application/vnd.github+json")
    @retrofit2.http.PUT("repos/{user}/{repo}/contents/{path}")
    suspend fun putFile(
        @retrofit2.http.Path("user") user: String,
        @retrofit2.http.Path("repo") repo: String,
        @retrofit2.http.Path("path") path: String,
        @Body body: GhContentRequest
    ): retrofit2.Response<GhContentResponse>
}

object GitHubSync {
    private fun api(token: String): GitHubApi {
        val client = OkHttpClient.Builder()
            .addInterceptor { chain ->
                val req = chain.request().newBuilder()
                    .addHeader("Authorization", "Bearer $token")
                    .build()
                chain.proceed(req)
            }
            .addInterceptor(HttpLoggingInterceptor().apply {
                level = HttpLoggingInterceptor.Level.BASIC
            })
            .build()
        return Retrofit.Builder()
            .baseUrl("https://api.github.com/")
            .client(client)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(GitHubApi::class.java)
    }

    /**
     * Tarik daftar VPS dari repo (pull) -> simpan ke SQLite lokal.
     * Format per baris: ### username expiry ip
     */
    suspend fun pull(context: android.content.Context): String {
        val token = Prefs.getGhToken(context)
        if (token.isBlank()) return "Token GitHub kosong"
        val user = Prefs.getGhUser(context)
        val repo = Prefs.getGhRepo(context)
        val path = Prefs.getGhPath(context)
        if (user.isBlank() || repo.isBlank() || path.isBlank())
            return "Konfigurasi GitHub belum lengkap"
        return try {
            val api = api(token)
            val resp = api.getFile(user, repo, path)
            if (!resp.isSuccessful) {
                val err = resp.errorBody()?.string()?.take(200) ?: resp.message()
                return "Gagal tarik ($resp.code()): $err"
            }
            val b64 = resp.body()?.content ?: return "Konten kosong"
            val decoded = try {
                String(android.util.Base64.decode(b64, android.util.Base64.DEFAULT), Charsets.UTF_8)
            } catch (e: Exception) { return "Gagal decode konten" }
            val lines = decoded.lines()
                .map { it.trim() }
                .filter { it.startsWith("###") }
            val list = lines.mapNotNull { line ->
                val parts = line.removePrefix("###").trim().split("\\s+".toRegex())
                if (parts.size >= 3) {
                    Vps(
                        username = parts[0],
                        masaAktif = parts[1],
                        ipVps = parts[2]
                    )
                } else null
            }
            val db = VpsDbHelper(context)
            // Pertahankan kredensial SSH lokal (user/pass tidak di-sync ke repo)
            val localByKey = db.getAll().associateBy { "${it.username}|${it.ipVps}" }
            val merged = list.map { pulled ->
                val local = localByKey["${pulled.username}|${pulled.ipVps}"]
                if (local != null && pulled.userSsh.isBlank() && pulled.passSsh.isBlank()) {
                    pulled.copy(userSsh = local.userSsh, passSsh = local.passSsh, serverAktif = local.serverAktif)
                } else pulled
            }
            db.replaceAll(merged)
            "Berhasil tarik ${merged.size} data dari GitHub (kredensial SSH lokal dipertahankan)"
        } catch (e: Exception) {
            "Error: ${e.message ?: e.javaClass.simpleName}"
        }
    }

    /**
     * Push daftar VPS lokal ke repo (replace isi file).
     */
    private fun buildFileContent(list: List<Vps>): String {
        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        val today = sdf.format(Date())
        val sb = StringBuilder()
        sb.append("# VPS List — generated by ManageSC-Android\n")
        sb.append("# format: ### username expiry ip\n")
        sb.append("# updated: $today\n\n")
        for (v in list) {
            sb.append("### ${v.username} ${v.masaAktif} ${v.ipVps}\n")
        }
        return sb.toString()
    }

    /**
     * Push daftar VPS ke GitHub. Mengembalikan true jika sukses.
     * Catatan: implementasi ini meng-UPLOAD konten baru; untuk update file yang sudah ada
     * diperlukan SHA dari GET terlebih dahulu. Untuk simplifikasi, kita GET dulu lalu PUT.
     */
    suspend fun sync(context: android.content.Context): String {
        val token = Prefs.getGhToken(context)
        if (token.isBlank()) return "Token GitHub kosong"
        val user = Prefs.getGhUser(context)
        val repo = Prefs.getGhRepo(context)
        val path = Prefs.getGhPath(context)
        if (user.isBlank() || repo.isBlank() || path.isBlank())
            return "Konfigurasi GitHub belum lengkap"

        val list = VpsDbHelper(context).getAll()
        val content = buildFileContent(list)
        val b64 = android.util.Base64.encodeToString(
            content.toByteArray(Charsets.UTF_8), android.util.Base64.NO_WRAP
        )
        return try {
            val api = api(token)
            // Coba GET sha dulu (jika file ada)
            var sha: String? = null
            try {
                val getResp = api.getFile(user, repo, path)
                if (getResp.isSuccessful) sha = getResp.body()?.sha
            } catch (e: Exception) {
                // file mungkin belum ada -> sha tetap null (PUT akan buat baru)
            }

            val resp = api.putFile(
                user, repo, path,
                GhContentRequest("Update VPS list from ManageSC-Android", b64, sha)
            )
            if (resp.isSuccessful) "Berhasil sync ${list.size} data ke GitHub ($path)"
            else {
                val err = resp.errorBody()?.string()?.take(300) ?: resp.message()
                "Gagal sync (${resp.code()}): $err"
            }
        } catch (e: Exception) {
            "Error: ${e.message ?: e.javaClass.simpleName}"
        }
    }
}
